### ISSUE TITLE
Request support for Mac installation

### ISSUE THREAD

**Issue by CWagner23** [nasa-jpl/ion-core#1]
## Description
It does not appear possible to compile and install ION-Core on a Mac. This may be desirable to expand access to ION-Core, especially now that 3rd party software such as [Pyion](https://pyion.readthedocs.io/en/latest/) have added support for using ION in Python.  Mac support would allow development in a native environment which can be more convenient than having to dual boot or use VMs such as Parallels or Docker.  

## Current Behavior
I tried installing ION-Core on my (Intel chip) Mac but I received a fatal error when running the Makefile related to a missing '../../utils/bpsecadmin_config.h' file. 
 
I followed the instructions in the [README](https://github.com/nasa-jpl/ion-core/blob/4.1.2/README.md) for version 4.1.2. The previous steps completed successfully (ie wget, tar, extract.sh). Once I ran the Make command, there were several errors including: 
 
```
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform.c:542:12: error: redeclaration of 'sys_nerr' with a different type: 'int' vs 'const int'
extern int      sys_nerr;
```

```
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform.c:543:14: error: redeclaration of 'sys_errlist' with a different type: 'char *[]' vs 'const char *const []'
extern char     *sys_errlist[];
```

```
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform.c:2477:19: error: use of undeclared identifier 'MAXHOSTNAMELEN'
        char    hostnameBuf[MAXHOSTNAMELEN + 1];
                            ^
```
```
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform_sm.c:3423:39: error: use of undeclared identifier 'PTHREAD_CREATE_JOINABLE'
        oK(pthread_attr_setdetachstate(attr, PTHREAD_CREATE_JOINABLE));
```
```
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bpsec_policy_rule.c:38:10: fatal error: '../../utils/bpsecadmin_config.h' file not found
#include "../../utils/bpsecadmin_config.h"
```

**Comment by CWagner23** [comment]
The full output from running `make` is as follows:

```
/usr/bin/make -f /Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/mdir/bping.mk
/usr/bin/gcc -g -Wall -DSPACE_ORDER=3 -Wall -DBP_EXTENDED -lm -pthread \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbp.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/zco.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sdrxn.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sdrmgt.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/ion.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbpP.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform_sm.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sdrlist.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sdrcatlg.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bulk.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/smlist.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/psm.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/memmgr.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/lyst.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sptrace.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/smrbt.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/rfx.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sdrstring.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sdrhash.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/ionsec.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bpsec_policy.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bpsec_instr.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bei.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libimcfw.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/eureka.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/cbor.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/crc.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bcb.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bib.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bibe.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/saga.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sdrtable.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/radix.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bpsec_policy_eventset.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bpsec_policy_rule.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bpsec_util.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bpsec_asb.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/pnb.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bpq.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/meb.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bae.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/hcb.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/snw.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/imc.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sci.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bpsec_policy_event.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sc_value.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/csi.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sci_valmap.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sc_util.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/ion_test_sc.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bib_hmac_sha2_sc.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bcb_aes_gcm_sc.c \
	/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/rfc9173_utils.c \
	-I/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/inc \
	-lm -pthread \
	-o /Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/bin/bping
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:98:6: warning: implicit declaration of function 'pthread_equal' is invalid in C99 [-Wimplicit-function-declaration]
        && !pthread_equal(sendRequestsThread, pthread_self()))
            ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:98:40: warning: implicit declaration of function 'pthread_self' is invalid in C99 [-Wimplicit-function-declaration]
        && !pthread_equal(sendRequestsThread, pthread_self()))
                                              ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:149:6: warning: implicit declaration of function 'gettimeofday' is invalid in C99 [-Wimplicit-function-declaration]
                if(gettimeofday(&tvNow, NULL) < 0) {
                   ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:152:4: warning: implicit declaration of function 'pthread_exit' is invalid in C99 [-Wimplicit-function-declaration]
                        pthread_exit(NULL);
                        ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:175:6: warning: implicit declaration of function 'pthread_mutex_lock' is invalid in C99 [-Wimplicit-function-declaration]
                if(pthread_mutex_lock(&sdrmutex) != 0)
                   ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:179:4: warning: implicit declaration of function 'pthread_exit' is invalid in C99 [-Wimplicit-function-declaration]
                        pthread_exit(NULL);
                        ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:190:4: warning: implicit declaration of function 'pthread_exit' is invalid in C99 [-Wimplicit-function-declaration]
                        pthread_exit(NULL);
                        ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:196:6: warning: implicit declaration of function 'pthread_mutex_unlock' is invalid in C99 [-Wimplicit-function-declaration]
                if(pthread_mutex_unlock(&sdrmutex) != 0)
                   ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:200:4: warning: implicit declaration of function 'pthread_exit' is invalid in C99 [-Wimplicit-function-declaration]
                        pthread_exit(NULL);
                        ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:294:5: warning: implicit declaration of function 'gettimeofday' is invalid in C99 [-Wimplicit-function-declaration]
        if(gettimeofday(&tvNow, NULL) < 0) {
           ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:349:6: warning: implicit declaration of function 'pthread_mutex_lock' is invalid in C99 [-Wimplicit-function-declaration]
                if(pthread_mutex_lock(&sdrmutex) != 0)
                   ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:355:4: warning: implicit declaration of function 'pthread_exit' is invalid in C99 [-Wimplicit-function-declaration]
                        pthread_exit(NULL);
                        ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:363:4: warning: implicit declaration of function 'pthread_exit' is invalid in C99 [-Wimplicit-function-declaration]
                        pthread_exit(NULL);
                        ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:373:4: warning: implicit declaration of function 'pthread_exit' is invalid in C99 [-Wimplicit-function-declaration]
                        pthread_exit(NULL);
                        ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:375:6: warning: implicit declaration of function 'pthread_mutex_unlock' is invalid in C99 [-Wimplicit-function-declaration]
                if(pthread_mutex_unlock(&sdrmutex) != 0)
                   ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:381:4: warning: implicit declaration of function 'pthread_exit' is invalid in C99 [-Wimplicit-function-declaration]
                        pthread_exit(NULL);
                        ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:456:5: warning: implicit declaration of function 'gettimeofday' is invalid in C99 [-Wimplicit-function-declaration]
        if(gettimeofday(&tvStart, NULL) < 0) {
           ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:510:5: warning: implicit declaration of function 'pthread_mutex_init' is invalid in C99 [-Wimplicit-function-declaration]
        if(pthread_mutex_init(&sdrmutex, NULL) != 0)
           ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:550:5: warning: implicit declaration of function 'pthread_create' is invalid in C99 [-Wimplicit-function-declaration]
        if(pthread_begin(&receiveResponsesThread, NULL, receiveResponses,
           ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/inc/platform_sm.h:43:67: note: expanded from macro 'pthread_begin'
#define pthread_begin(...) GET_MACRO(__VA_ARGS__, pthread_begin5, pthread_begin4)(__VA_ARGS__)
                                                                  ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:550:5: warning: declaration of built-in function 'pthread_create' requires inclusion of the header <pthread.h>
      [-Wbuiltin-requires-header]
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/inc/platform_sm.h:43:67: note: expanded from macro 'pthread_begin'
#define pthread_begin(...) GET_MACRO(__VA_ARGS__, pthread_begin5, pthread_begin4)(__VA_ARGS__)
                                                                  ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bping.c:571:2: warning: implicit declaration of function 'pthread_join' is invalid in C99 [-Wimplicit-function-declaration]
        pthread_join(sendRequestsThread, NULL);
        ^
21 warnings generated.
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbp.c:588:6: warning: implicit declaration of function 'pthread_mutex_init' is invalid in C99 [-Wimplicit-function-declaration]
        if (pthread_mutex_init(&mutex, NULL))
            ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbp.c:596:6: warning: implicit declaration of function 'pthread_cond_init' is invalid in C99 [-Wimplicit-function-declaration]
        if (pthread_cond_init(&cv, NULL))
            ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbp.c:606:2: warning: implicit declaration of function 'pthread_mutex_lock' is invalid in C99 [-Wimplicit-function-declaration]
        pthread_mutex_lock(&mutex);
        ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbp.c:607:11: warning: implicit declaration of function 'pthread_cond_timedwait' is invalid in C99 [-Wimplicit-function-declaration]
        result = pthread_cond_timedwait(&cv, &mutex, &deadline);
                 ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbp.c:608:2: warning: implicit declaration of function 'pthread_mutex_unlock' is invalid in C99 [-Wimplicit-function-declaration]
        pthread_mutex_unlock(&mutex);
        ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbp.c:609:2: warning: implicit declaration of function 'pthread_mutex_destroy' is invalid in C99 [-Wimplicit-function-declaration]
        pthread_mutex_destroy(&mutex);
        ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbp.c:610:2: warning: implicit declaration of function 'pthread_cond_destroy' is invalid in C99 [-Wimplicit-function-declaration]
        pthread_cond_destroy(&cv);
        ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbp.c:737:5: warning: implicit declaration of function 'pthread_join' is invalid in C99 [-Wimplicit-function-declaration]
                                pthread_join(timerThread, NULL);
                                ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbp.c:744:6: warning: implicit declaration of function 'pthread_cancel' is invalid in C99 [-Wimplicit-function-declaration]
                                        pthread_end(timerThread);
                                        ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/inc/platform_sm.h:65:25: note: expanded from macro 'pthread_end'
#define pthread_end(x)          pthread_cancel(x)
                                ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbp.c:745:6: warning: implicit declaration of function 'pthread_join' is invalid in C99 [-Wimplicit-function-declaration]
                                        pthread_join(timerThread, NULL);
                                        ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbp.c:755:5: warning: implicit declaration of function 'pthread_cancel' is invalid in C99 [-Wimplicit-function-declaration]
                                pthread_end(timerThread);
                                ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/inc/platform_sm.h:65:25: note: expanded from macro 'pthread_end'
#define pthread_end(x)          pthread_cancel(x)
                                ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbp.c:756:5: warning: implicit declaration of function 'pthread_join' is invalid in C99 [-Wimplicit-function-declaration]
                                pthread_join(timerThread, NULL);
                                ^
12 warnings generated.
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform.c:542:12: error: redeclaration of 'sys_nerr' with a different type: 'int' vs 'const int'
extern int      sys_nerr;
                ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:367:20: note: previous declaration is here
extern __const int sys_nerr;            /* perror(3) external variables */
                   ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform.c:543:14: error: redeclaration of 'sys_errlist' with a different type: 'char *[]' vs 'const char *const []'
extern char     *sys_errlist[];
                 ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:368:30: note: previous declaration is here
extern __const char *__const sys_errlist[];
                             ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform.c:552:9: warning: returning 'const char *const' from a function with result type 'char *' discards qualifiers
      [-Wincompatible-pointer-types-discards-qualifiers]
        return sys_errlist[errno];
               ^~~~~~~~~~~~~~~~~~
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform.c:562:9: warning: implicit declaration of function 'cuserid' is invalid in C99 [-Wimplicit-function-declaration]
        return cuserid(buffer);
               ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform.c:562:9: warning: incompatible integer to pointer conversion returning 'int' from a function with result type 'char *'
      [-Wint-conversion]
        return cuserid(buffer);
               ^~~~~~~~~~~~~~~
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform.c:614:5: warning: implicit declaration of function 'gettimeofday' is invalid in C99 [-Wimplicit-function-declaration]
        oK(gettimeofday(tvp, NULL));
           ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform.c:1379:10: warning: implicit declaration of function 'memalign' is invalid in C99 [-Wimplicit-function-declaration]
        block = memalign((size_t) (sizeof(void *)), size);
                ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform.c:1379:8: warning: incompatible integer to pointer conversion assigning to 'void *' from 'int' [-Wint-conversion]
        block = memalign((size_t) (sizeof(void *)), size);
              ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform.c:2477:19: error: use of undeclared identifier 'MAXHOSTNAMELEN'
        char    hostnameBuf[MAXHOSTNAMELEN + 1];
                            ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform.c:2512:20: error: use of undeclared identifier 'MAXHOSTNAMELEN'
        char            hostnameBuf[MAXHOSTNAMELEN + 1];
                                    ^
6 warnings and 4 errors generated.
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sdrxn.c:422:24: warning: implicit declaration of function 'pthread_self' is invalid in C99 [-Wimplicit-function-declaration]
        sdr->sdrOwnerThread = pthread_self();
                              ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sdrxn.c:422:22: warning: incompatible integer to pointer conversion assigning to 'pthread_t' (aka 'struct _opaque_pthread_t *') from 'int'
      [-Wint-conversion]
        sdr->sdrOwnerThread = pthread_self();
                            ^ ~~~~~~~~~~~~~~
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sdrxn.c:437:5: warning: implicit declaration of function 'pthread_equal' is invalid in C99 [-Wimplicit-function-declaration]
        && pthread_equal(sdr->sdrOwnerThread, pthread_self()))
           ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sdrxn.c:437:40: warning: implicit declaration of function 'pthread_self' is invalid in C99 [-Wimplicit-function-declaration]
        && pthread_equal(sdr->sdrOwnerThread, pthread_self()))
                                              ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sdrxn.c:459:5: warning: implicit declaration of function 'pthread_equal' is invalid in C99 [-Wimplicit-function-declaration]
        && pthread_equal(sdr->sdrOwnerThread, pthread_self()))
           ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sdrxn.c:459:40: warning: implicit declaration of function 'pthread_self' is invalid in C99 [-Wimplicit-function-declaration]
        && pthread_equal(sdr->sdrOwnerThread, pthread_self()))
                                              ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sdrxn.c:1815:6: warning: implicit declaration of function 'pthread_equal' is invalid in C99 [-Wimplicit-function-declaration]
                && pthread_equal(sdrv->sdr->sdrOwnerThread, pthread_self()));
                   ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/sdrxn.c:1815:47: warning: implicit declaration of function 'pthread_self' is invalid in C99 [-Wimplicit-function-declaration]
                && pthread_equal(sdrv->sdr->sdrOwnerThread, pthread_self()));
                                                            ^
8 warnings generated.
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/ion.c:1634:19: error: use of undeclared identifier 'MAXHOSTNAMELEN'
        char    ownHostName[MAXHOSTNAMELEN + 1];
                            ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/ion.c:1676:34: error: use of undeclared identifier 'MAXHOSTNAMELEN'
                if (getNameOfHost(ownHostName, MAXHOSTNAMELEN) < 0)
                                               ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/ion.c:1990:24: warning: implicit declaration of function 'pthread_self' is invalid in C99 [-Wimplicit-function-declaration]
                proc[i].mainThread = pthread_self();
                                     ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/ion.c:1990:22: warning: incompatible integer to pointer conversion assigning to 'pthread_t' (aka 'struct _opaque_pthread_t *') from 'int'
      [-Wint-conversion]
                proc[i].mainThread = pthread_self();
                                   ^ ~~~~~~~~~~~~~~
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/ion.c:2018:7: warning: implicit declaration of function 'pthread_equal' is invalid in C99 [-Wimplicit-function-declaration]
        if (!pthread_equal(mainThread, pthread_self()))
             ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/ion.c:2018:33: warning: implicit declaration of function 'pthread_self' is invalid in C99 [-Wimplicit-function-declaration]
        if (!pthread_equal(mainThread, pthread_self()))
                                       ^
4 warnings and 2 errors generated.
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbpP.c:509:20: error: use of undeclared identifier 'MAXHOSTNAMELEN'
        char            hostNameBuf[MAXHOSTNAMELEN + 1];
                                    ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbpP.c:558:30: error: use of undeclared identifier 'MAXHOSTNAMELEN'
                getNameOfHost(hostNameBuf, MAXHOSTNAMELEN);
                                           ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbpP.c:1093:4: warning: implicit declaration of function 'pthread_join' is invalid in C99 [-Wimplicit-function-declaration]
                        pthread_join(vduct->cloThread, NULL);
                        ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/libbpP.c:1942:6: warning: implicit declaration of function 'gettimeofday' is invalid in C99 [-Wimplicit-function-declaration]
        if (gettimeofday(&tv, NULL) < 0)
            ^
2 warnings and 2 errors generated.
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform_sm.c:2429:11: warning: implicit declaration of function 'pthread_create' is invalid in C99 [-Wimplicit-function-declaration]
        result = pthread_begin(thread, attr, start_routine, arg);
                 ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/inc/platform_sm.h:43:67: note: expanded from macro 'pthread_begin'
#define pthread_begin(...) GET_MACRO(__VA_ARGS__, pthread_begin5, pthread_begin4)(__VA_ARGS__)
                                                                  ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform_sm.c:2429:11: warning: declaration of built-in function 'pthread_create' requires inclusion of the header <pthread.h>
      [-Wbuiltin-requires-header]
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/inc/platform_sm.h:43:67: note: expanded from macro 'pthread_begin'
#define pthread_begin(...) GET_MACRO(__VA_ARGS__, pthread_begin5, pthread_begin4)(__VA_ARGS__)
                                                                  ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform_sm.c:3417:5: warning: implicit declaration of function 'pthread_attr_init' is invalid in C99 [-Wimplicit-function-declaration]
        oK(pthread_attr_init(attr));
           ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform_sm.c:3419:5: warning: implicit declaration of function 'pthread_attr_setschedpolicy' is invalid in C99
      [-Wimplicit-function-declaration]
        oK(pthread_attr_setschedpolicy(attr, SCHED_FIFO));
           ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform_sm.c:3421:5: warning: implicit declaration of function 'pthread_attr_setschedparam' is invalid in C99
      [-Wimplicit-function-declaration]
        oK(pthread_attr_setschedparam(attr, &parms));
           ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform_sm.c:3423:5: warning: implicit declaration of function 'pthread_attr_setdetachstate' is invalid in C99
      [-Wimplicit-function-declaration]
        oK(pthread_attr_setdetachstate(attr, PTHREAD_CREATE_JOINABLE));
           ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform_sm.c:3423:39: error: use of undeclared identifier 'PTHREAD_CREATE_JOINABLE'
        oK(pthread_attr_setdetachstate(attr, PTHREAD_CREATE_JOINABLE));
                                             ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/platform_sm.c:3426:6: warning: implicit declaration of function 'pthread_attr_setstacksize' is invalid in C99
      [-Wimplicit-function-declaration]
                oK(pthread_attr_setstacksize(attr, stackSize));
                   ^
7 warnings and 1 error generated.
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/psm.c:163:15: warning: implicit declaration of function 'pthread_self' is invalid in C99 [-Wimplicit-function-declaration]
        selfThread = pthread_self();
                     ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/psm.c:163:13: warning: incompatible integer to pointer conversion assigning to 'pthread_t' (aka 'struct _opaque_pthread_t *') from 'int'
      [-Wint-conversion]
        selfThread = pthread_self();
                   ^ ~~~~~~~~~~~~~~
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/psm.c:165:5: warning: implicit declaration of function 'pthread_equal' is invalid in C99 [-Wimplicit-function-declaration]
        && pthread_equal(map->ownerThread, selfThread))
           ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/psm.c:182:5: warning: implicit declaration of function 'pthread_equal' is invalid in C99 [-Wimplicit-function-declaration]
        && pthread_equal(map->ownerThread, pthread_self()))
           ^
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/psm.c:182:37: warning: implicit declaration of function 'pthread_self' is invalid in C99 [-Wimplicit-function-declaration]
        && pthread_equal(map->ownerThread, pthread_self()))
                                           ^
5 warnings generated.
/Users/ctwagne1/Documents/Projects/CADRE/Code/ion-core/src/bpsec_policy_rule.c:38:10: fatal error: '../../utils/bpsecadmin_config.h' file not found
#include "../../utils/bpsecadmin_config.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [all] Error 1
make: *** [all] Error 2

```

**Comment by iondev33** [comment]
A beta prototype has been developed to build ion-core on macOS 14.7, along with other feature. It will become available by the end of October.

**Comment by iondev33** [comment]
The build system has been updated to compile on macOS, tested on macOS 14.7 for now. Please check tag 4.1.3s-a.1.

However, running ION on mac will also require updates to the default kernel settings for network buffer size and shared memory so that sufficient memory can be provisioned for ION operation. For that level of details, please look at the script under /scripts/macos to check and update the macOS. 

We will close this issue for now but feel free to re-open if you have trouble building on macOS.
